apiVersion: v1
kind: Pod
metadata:
  name: assignment2-csdp1344
spec:
  containers:
  - name: nginx
    image: nginx:1.23.3-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: "500Mi"
      requests:
        cpu: "0.5"
        memory: "200Mi"